package org.example.kafka;

import lombok.extern.slf4j.Slf4j;
import org.example.kafka.PatientEvent; // Generated by protoc from patient_event.proto
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;

// @Slf4j is a Lombok annotation that auto-generates a `log` field backed by SLF4J.
// This saves us from writing: private static final Logger log = LoggerFactory.getLogger(KafkaProducer.class);
@Slf4j
// @Service registers this class as a Spring bean so it can be injected into other components (e.g. PatientService).
@Service
public class KafkaProducer {

    // KafkaTemplate is Spring's abstraction over the Kafka producer client.
    // <String, byte[]> means:
    //   - String  → the message key (used by Kafka to decide which partition to route the message to)
    //   - byte[]  → the message value (we send raw protobuf bytes instead of JSON for efficiency)
    private final KafkaTemplate<String, byte[]> kafkaTemplate;

    // Spring injects the KafkaTemplate automatically via constructor injection.
    public KafkaProducer(KafkaTemplate<String, byte[]> kafkaTemplate) {
        this.kafkaTemplate = kafkaTemplate;
    }

    public void sendEvent(PatientEvent event) {
        log.info("Sending kafka event: {}", event);
        // event.toByteArray() serialises the protobuf object into a compact binary format.
        // We then publish those bytes to the Kafka topic named "patient".
        // Any service consuming the "patient" topic can deserialise the bytes back
        // into a PatientEvent using PatientEvent.parseFrom(bytes).
        kafkaTemplate.send("patient", event.toByteArray());
    }
}
