spring.application.name=patient-service

# PostgreSQL datasource
# When running via Docker Compose use the service name "postgres" as the host.
# When running locally, change to localhost:5432
spring.datasource.url=jdbc:postgresql://postgres:5432/patientdb
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=4000

logging.level.root=INFO